desc "Build tutorial.js"
task :build do
  gem 'dare', '0.1.2'
  gem 'opal', '0.7.0beta3'
  gem 'opal-jquery', '0.3.0beta1'
  require 'opal'
  require 'opal-jquery'
  Opal::Processor.source_map_enabled = false
  Opal::Processor.inline_operators_enabled = true
  env = Sprockets::Environment.new
  Opal.paths.each do |path|
    env.append_path path
  end
  env.append_path "."
  env.append_path `bundle show dare`.chomp + '/lib'

  File.open("tutorial.js", "w+") do |out|
    out << env["tutorial"].to_s
  end
end