gem 'opal', '0.6.3'
require 'opal'
require 'opal-jquery'

desc "Build pong.js"
task :build do
  Opal::Processor.source_map_enabled = false
  env = Sprockets::Environment.new
  Opal.paths.each do |path|
    env.append_path path
  end
  env.append_path "."
  env.append_path "../../lib"

  File.open("pong.js", "w+") do |out|
    out << env["pong"].to_s
  end
end