desc "Build mario.js"
task :build do
  require 'opal'
  require 'opal-jquery'

  env = Opal::Environment.new
  env.append_path "."
  env.append_path "../../lib"

  File.open("mario.js", "w+") do |out|
    out << env["mario"].to_s
  end
end