require 'opal'
require 'opal-jquery'

desc "Build mario.js"
task :build do
  Opal::Processor.source_map_enabled = false
  Opal::Processor.inline_operators_enabled = true

  env = Sprockets::Environment.new
  Opal.paths.each do |path|
    env.append_path path
  end
  env.append_path "."
  env.append_path "../../lib"

  File.open("mario.js", "w+") do |out|
    out << env["mario"].to_s
  end
end
